### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by StefanScherer** [pecigonzalo/docker-machine-vmwareworkstation#1]
Thanks for making this driver plugin. I have built a [Chocolatey package `docker-machine-vmwareworkstation`](https://chocolatey.org/packages/docker-machine-vmwareworkstation/0.9.0) which is in review at the moment. But anyone can use it already with

```
choco install docker-machine-vmwareworkstation -version 0.9.0
```

This also installs the docker-machine Chocolatey package.

**Comment by pecigonzalo** [comment]
Great stuff! is there anything i can do to help with that or make it easier for you to maintain the choco package?

**Comment by StefanScherer** [comment]
Oh, just got first feedback from package review:

```
'docker-machine-vmwareworkstation' is Submitted.
doc left the following comment(s):

The site of the project should be this:
https://github.com/pecigonzalo/docker-machine-vmwareworkstation

docker-machine-vmwareworkstation is marked as a Pre-release:
https://github.com/pecigonzalo/docker-machine-vmwareworkstation/releases
If the program is supposed to be stable some day, for the pre-releases you would have to change the version to for example 0.9.0-prerelease (it doesn't have to be 0.9.0-prerelease, it can be 0.9.0-alpha, 0.9.0-beta or whatever you want). Those would be exempted versions and you would have to install them using choco install docker-machine-vmwareworkstation -pre
```

Your release 0.9.0 is marked as pre-release. I've tested it today and it worked out of the box. IMHO it is worth a release and not just a pre-release. As the next version probably has a higher version number this is fine thesedays ;-)

You may find the Chocolatey package sources here: https://github.com/StefanScherer/choco-docker-machine-vmwareworkstation

I first thought of sending you a PR with the few files and put it into your repo as well. This might also work very vell with AppVeyor doing a "go build", some unit tests, publish the binary as a github release if it was a `git push --tags` and then also build and test the choco package and deploy it to chocolatey.org. Could all be done in one appveyor.yml.

But I can make you a collaborator to my choco repo. No problem at all.

I tested it in a Windows 10 VM with
- Installing Chocolatey
- `choco install -y vmwareworkstation` and activated the license
- `choco install -y docker-machine-vmwareworkstation` and then
- `docker-machine create -d vmwareworkstation dev`

Worked out of the box, but haven't used it further. But at work I'll install it on a DELL notebook and use it in parallel to VirtualBox...

**Comment by pecigonzalo** [comment]
The idea of merging it to this project with a PR so we can then automate it with appveyor sounds good, if you are still keen on that ill love to do that and help get it done. 

One of the reasons i didnt mark it as release is because i dont have any testing on the build/functionality as of yet, but im ok to change the name of the prerelease versions to append the "-prerelease" ill do that today.

**Comment by StefanScherer** [comment]
I think you can leave the 0.9.0 release as it is. The reviewer at chocolatey suggested the suffix for the choco package if you plan to release a "final release" still as 0.9.0. But I think you will increase the version number so there is no need for such a suffix.

And yes, a merge of the two repos would look even better as the complete build and deployment is done in one repo.

To build a go binary at http://www.appveyor.com there is eg. a build for packer: https://github.com/mitchellh/packer/blob/master/appveyor.yml

I used AppVeyor to build C++ programs and deploy it as a GitHub release, eg. here: https://github.com/StefanScherer/win-getaddrinfo/blob/master/appveyor.yml

So we only have to put all pieces together...

**Comment by pecigonzalo** [comment]
Ill start the appveyor stuff i have an account and all.
Btw your c++ app, you are publishing your token, i dont think that is recommended.

**Comment by pecigonzalo** [comment]
Initial AppVeyor is set, ill start building some more test cases, feel free to submit a PR for the choco stuff.

**Comment by pecigonzalo** [comment]
Ill close this if you agree.

**Comment by StefanScherer** [comment]
Sure. I'll send a PR for choco later.
