### ISSUE TITLE
Workstation version needed ?

### ISSUE THREAD

**Issue by osaris** [pecigonzalo/docker-machine-vmwareworkstation#16]
Thx again for this nice piece of code, performances of virtualbox volumes on windows are aweful and VMWare workstation is far better ! 

I'm currently evaluating this driver with VMWare Workstation 12 Pro but the README file is not clear about which version of VMWare Workstation is needed ? (pro ? player ? free player ?).

**Comment by steventsvetkov** [comment]
From what I've tested, it works with free and pro. It should work for all, I believe, there isn't any difference in the way VMWare Workstation works at the core level.

**Comment by osaris** [comment]
That also was my opinion but from what I've tested, I can't start the VM with `docker-machine` command with free/player ? (stuck on `Starting "dev"...`) No problem while running Workstation Pro.

Note that I've rebuilt my VM when changing version and I can start the VM from VMWare app without problem in both cases.

**Comment by steventsvetkov** [comment]
Navigate to the location with the virtual machine, there should be a log there from the last time you attempted to start the machine with docker-machine. The default location for the docker machines is `C:\Users\(your user)\.docker\machines\(your machine).` Include it here and we will have to see what @pecigonzalo has to say about this.

**Comment by pecigonzalo** [comment]
@osaris 

The driver uses vmrun in the background to perform actions, it should run VMware workstation 10+ .
Ill verify the versions and update the README.
All of the versions should run on VMware 11+ (pro, player, free player). On old versions (where vmware player had a lot more limitations and was not based on workstations as it seems to be now) it will only work on Workstation.

Sorry about the confusion, but in the last versions VMware made a mess of the different features/versions.

Also, please submit the log as Stev3nT mentioned.

**Comment by osaris** [comment]
I reinstalled player free to test and I have no log in the folder of the VM after running `docker-machine start dev` :

```
 Répertoire de C:\Users\Raphael\.docker\machine\machines\dev

18.04.2016  19:45    <DIR>          .
18.04.2016  19:45    <DIR>          ..
18.04.2016  19:45        36 700 160 boot2docker.iso
18.04.2016  19:45             2 564 config.json
18.04.2016  19:45                 0 dev.vmsd
18.04.2016  19:45             1 798 dev.vmx
18.04.2016  19:45    <DIR>          dev.vmx.lck
18.04.2016  19:45               258 dev.vmxf
18.04.2016  19:45             1 679 id_rsa
18.04.2016  19:45               381 id_rsa.pub
```

**Comment by osaris** [comment]
Looking at https://github.com/pecigonzalo/docker-machine-vmwareworkstation/blob/6026614c2ac9cdfe3bae80302e4a559ddc85de55/vmrun.go I can't find anything related to `VMware player` folder (only to `VMWare workstation`) in `workstationProgramFilePaths`` method.

Moreover `workstationVMwareRoot` is looking for `vmware.exe` which doesn't exist when using player (only `vmplayer.exe` key exists).

**Comment by pecigonzalo** [comment]
Sorry for the delay, my laptop is under repair.
run: `docker-machine -d start dev` that should output debug log, then past it here.

Osaris, you are correct, i missremember the lookup function. I just took a look at it, and if you have the vmrun file you can use `VMWARE_HOME` environment variable to specify its location. Ill add that to the README as well.
