### ISSUE TITLE
[v1.0.0] ssh key not being created

### ISSUE THREAD

**Issue by jonl-percsolutions-com** [pecigonzalo/docker-machine-vmwareworkstation#18]
docker-machine : v0.7.0
docker-machine-vmwareworkstation: v 1.0.0
VMWare Workstation: Licensed v 10.0.7
Windows 7 64-bit

VM is created and started but server.pem ssh key is never created.  Rand create with --debug and nothing was output in regards to the ssh key.  Keep receiving message, waiting on ssh service.  Below is the full output of the log.

> Start interactive shell
> 
> me@mymachine MINGW64 ~
> $ docker-machine ls
> NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
> default   \*        virtualbox   Running   tcp://192.168.99.100:2376           v1.11.1
> 
> me@mymachine MINGW64 ~
> $ docker-machine --debug create --driver=vmwareworkstation dev
> Docker Machine Version:  0.7.0, build a650a40
> Found binary path at X:\Programs\Docker Toolbox\docker-machine-driver-vmwareworkstation.exe
> Launching plugin server for driver vmwareworkstation
> Plugin server listening at address 127.0.0.1:26935
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (flag-lookup) Calling .GetMachineName
> (flag-lookup) Calling .DriverName
> (flag-lookup) Calling .GetCreateFlags
> Found binary path at X:\Programs\Docker Toolbox\docker-machine-driver-vmwareworkstation.exe
> Launching plugin server for driver vmwareworkstation
> Plugin server listening at address 127.0.0.1:26939
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> (dev) Calling .GetMachineName
> (dev) Calling .DriverName
> (dev) Calling .GetCreateFlags
> (dev) Calling .SetConfigFromFlags
> Running pre-create checks...
> (dev) Calling .PreCreateCheck
> (dev) DBG | local Boot2Docker ISO version:  v1.11.1
> (dev) Calling .GetConfigRaw
> Creating machine...
> (dev) Calling .Create
> (dev) DBG | local Boot2Docker ISO version:  v1.11.1
> (dev) Copying X:\myhome.docker\machine\cache\boot2docker.iso to X:\myhome.docker\machine\machines\dev\boot2docker.iso...
> (dev) Creating SSH key...
> (dev) Creating VM...
> (dev) Creating disk 'X:\myhome.docker\machine\machines\dev\dev.vmdk'
> (dev) DBG | VixDiskLib: Invalid configuration file parameter.  Failed to read configuration file.
> (dev) Virtual disk creation successful.
> (dev) Starting dev...
> (dev) DBG | executing: X:/Programs/VMware/VMware Workstation/vmrun.exe start X:\myhome.docker\machine\machines\dev\dev.vmx nogui
> (dev) Waiting for VM to come online...
> (dev) DBG | MAC address in VMX: 00:0c:29:e5:84:5c
> (dev) DBG | IP found in DHCP lease table: 192.168.204.130
> (dev) DBG | Got an ip: 192.168.204.130
> (dev) DBG | SSH Daemon not responding yet: dial tcp 192.168.204.130:22: ConnectEx tcp: i/o timeout
> .......
> (dev) DBG | MAC address in VMX: 00:0c:29:e5:84:5c
> (dev) DBG | IP found in DHCP lease table: 192.168.204.130
> (dev) DBG | Got an ip: 192.168.204.130
> (dev) DBG | SSH Daemon not responding yet: dial tcp 192.168.204.130:22: ConnectEx tcp: i/o timeout
> 
> me@mymachine MINGW64 ~
> $ docker-machine ls
> NAME      ACTIVE   DRIVER              STATE     URL                          SWARM   DOCKER    ERRORS
> default   \*        virtualbox          Running   tcp://192.168.99.100:2376            v1.11.1
> dev       -        vmwareworkstation   Running   tcp://192.168.204.130:2376           Unknown   Unable to query docker version: Unable to read TLS config: open X:\myhome.docker\machine\machines\dev\server.pem: The system cannot find the file
> specified.
> 
> me@mymachine MINGW64 ~
> $

Attempted regenerate certs and still no go:

> Docker Machine Version:  0.7.0, build a650a40
> Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
> Regenerating TLS certificates
> Found binary path at X:\Programs\Docker Toolbox\docker-machine-driver-vmwareworkstation.exe
> Launching plugin server for driver vmwareworkstation
> Plugin server listening at address 127.0.0.1:27467
> () Calling .GetVersion
> Using API Version  1
> () Calling .SetConfigRaw
> () Calling .GetMachineName
> command=configureAuth machine=dev
> Waiting for SSH to be available...
> Getting to WaitForSSH function...
> (dev) Calling .GetSSHHostname
> (dev) DBG | executing: X:/Programs/VMware/VMware Workstation/vmrun.exe list
> (dev) DBG | MAC address in VMX: 00:0c:29:e5:84:5c
> (dev) DBG | IP found in DHCP lease table: 192.168.204.130
> (dev) Calling .GetSSHPort
> (dev) Calling .GetSSHKeyPath
> (dev) Calling .GetSSHKeyPath
> (dev) Calling .GetSSHUsername
> Using SSH client type: external
> &{[-F /dev/null -o BatchMode=yes -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o Co
> titiesOnly=yes -i X:\myhome.docker\machine\machines\dev\id_rsa -p 22] C:\Program Files\Git\usr\bin\ssh.exe <nil>}
> About to run SSH command:
> exit 0
> SSH cmd err, output: exit status 255:
> Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
> command : exit 0
> err     : exit status 255
> output  :

**Comment by pecigonzalo** [comment]
You are running this from mingw and from X: drive correct?
Could you try:
- mingw from C: drive
- powershell X:
- powershell C:

I believe it could be related to it running from a different drive.

Thanks

**Comment by jonl-percsolutions-com** [comment]
I am running from the C drive, I just obfuscated the paths to my home directory before posting the issue. 
However, i figured it out, the issue was that my NAT network was corrupted and the host was not receiving a valid ip on the appropriate network.

**Comment by jonl-percsolutions-com** [comment]
Closing issue due to vmware network configuration issue, unless you want to add a check on the ip address of the host.
