### ISSUE TITLE
VM does not mount the Users directory

### ISSUE THREAD

**Issue by JettJones** [pecigonzalo/docker-machine-vmwareworkstation#20]
Similarly to #19, I'm seeing the docker host coming up without the /c/Users/ file share. 

I'm running on `Windows 10 Pro` with
`vmware workstation 12.1.1 build-3770994`
`docker-machine 0.7.0` and `docker 1.11.1`

On the docker host VM, I only see one vmhgfs mount:

```
$ mount | grep vm
vmhgfs-fuse on /mnt/hgfs type fuse.vmhgfs-fuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
```

The only command I've run at that point `docker-machine create --driver vmwareworkstation default`. On a previous attempt I created a container with a volume mount `/c/Users/Jett:/testtest`. It looks like that step can create the `/c/Users/...`  path in the boot2docker VM.

This is (what I think is) the relevant part of the create debug output:

```
(default) DBG | Creating Tar key bundle...
(default) DBG | executing: C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe  directoryExistsInGuest C:\Users\Jett\.docker\machine\machines\default\default.vmx /var/lib/boot2docker
(default) DBG | executing: C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe  CopyFileFromHostToGuest C:\Users\Jett\.docker\machine\machines\default\default.vmx C:\Users\Jett\.docker\machine\machines\default\userdata.tar /home/docker/userdata.tar
(default) DBG | executing: C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe  runScriptInGuest C:\Users\Jett\.docker\machine\machines\default\default.vmx /bin/sh sudo /bin/mv /home/docker/userdata.tar /var/lib/boot2docker/userdata.tar && sudo tar xf /var/lib/boot2docker/userdata.tar -C /home/docker/ > /var/log/userdata.log 2>&1 && sudo chown -R docker:staff /home/docker
(default) DBG | executing: C:/Program Files (x86)/VMware/VMware Workstation/vmrun.exe  enableSharedFolders C:\Users\Jett\.docker\machine\machines\default\default.vmx
(default) Calling .GetConfigRaw
(default) Calling .DriverName
(default) Calling .DriverName
Waiting for machine to be running, this may take a few minutes...
```

when I run `vmrun enableSharedFolders` directly, it fails, saying an error occurred on the guest operating system.  I'm not sure why the next step with `vmhgfs-fuse` is skipped though.

Anyway - that's as far as I got digging into the debug output from re-running docker-machine provision or docker-machine create. If there are other details that could help debug, let me know.

Thanks.

**Comment by pecigonzalo** [comment]
What version where you running? latest build or latest release?

**Comment by JettJones** [comment]
v1.0.0 from here: https://github.com/pecigonzalo/docker-machine-vmwareworkstation/releases  I'll give the new version, 1.0.10 a try.

**Comment by JettJones** [comment]
1.0.10 fixes the file mount(s)!  Running `vmrun enableFileShares` on my host _still_ fails, so that's apparently not diagnostic.  I'm not sure which change in that set was fully responsible - maybe some of the simple path updates for windows.

In short, looks fixed in the latest build - I'll close this out.

**Comment by pecigonzalo** [comment]
@JettJones Thanks for reporting back, i believe the wrong artifact ended up as v1.0.0 as it was working in the past, ill rebuild it and correct that anyway, in case someone has issues with v1.0.10
