### ISSUE TITLE
Merge with upstream?

### ISSUE THREAD

**Issue by gtirloni** [pecigonzalo/docker-machine-vmwareworkstation#25]
First, thank you very much for working on this. It makes life more bearable for some of us using VMware.

I can report it worked great with VMware Workstation 12.1 on Windows 10 (AU).

Are you considering submitting this upstream to Docker?

**Comment by pecigonzalo** [comment]
@gtirloni Great to hear this! and i love knowing is helping other people.
I did submit this upstream, but i was asked by the docker team to keep it as plugin.

You can check the info here: https://github.com/docker/machine/pull/2300

**Comment by gtirloni** [comment]
It's unfortunate they won't accept it. It would be a much better experience for end users (and the driver could always be dropped if they lack the bandwidth to support it).

I guess now that they have released Docker for Win/Mac and it depends on Hyper-V/xhyve, we might not be seeing much activity on Docker Machine and Docker Toolbox, but that's just a hunch.

Thanks again, really appreciated!

**Comment by StefanScherer** [comment]
@gtirloni Just curious. How do you have installed docker-machine and this plugin? Through Chocolatey or downloaded the binaries manually?

**Comment by gtirloni** [comment]
@StefanScherer I downloaded the plugin manually and put it in the Docker Toolbox folder like [this](https://github.com/docker/toolbox/issues/107#issuecomment-237257075).

**Comment by StefanScherer** [comment]
@gtirloni Thanks for the link and how you made it work for you.

**Comment by pecigonzalo** [comment]
@gtirloni Mind if i put those steps on the README? they might help other people

**Comment by gtirloni** [comment]
No worries. Thank you.
