### ISSUE TITLE
Cannot initiate docker machine in symlink path

### ISSUE THREAD

**Issue by festum** [pecigonzalo/docker-machine-vmwareworkstation#32]
OS: Windows 10 build 14393 x64
VMware Workstation Pro v12.5.2
docker-machine-vmwareworkstation v1.0.10

Using symlink for path C:\Users\{USER}\.docker\machine will get `Error creating machine: Error waiting for machine to be running: Maximum number of retries (60) exceeded`.

![log](http://i.imgur.com/5A84YvL.png)

**Comment by pecigonzalo** [comment]
Sorry that i did not tag/reply sooner, i just saw this issue.

**Comment by masaeedu** [comment]
Seeing the same issue when I symlink the entire .docker folder from another drive. Being able to symlink this folder is useful, because the VMDK starts taking up considerable space with heavy use.

**Comment by pecigonzalo** [comment]
@masaeedu @Festum does the same happen on lets say, virtualbox driver?

**Comment by pecigonzalo** [comment]
@masaeedu @Festum This should be fixed now. Please let me know if it doesnt.

**Comment by festum** [comment]
@pecigonzalo It working fine now :)
