### ISSUE TITLE
Waiting for SSH to be available... (waiting forever)

### ISSUE THREAD

**Issue by zd-dalibor** [pecigonzalo/docker-machine-vmwareworkstation#34]
With vmware workstation v12.5.2 commands:

```shell
$ docker-machine create --driver=vmwareworkstation dev #or
$ docker-machine start dev
```

stuck on message `Waiting for SSH to be available...`.

**Comment by StefanScherer** [comment]
Try with debug output `docker-machine -D ...`. Which version of `docker-machine.exe` do you use?

**Comment by zd-dalibor** [comment]
@StefanScherer Something is messed up with my vmware virtual network. When I restored everything to default in vmware virtual network editor docker-machine commands started to work.
