### ISSUE TITLE
How to get Kitematic running?

### ISSUE THREAD

**Issue by drschlaumeier** [pecigonzalo/docker-machine-vmwareworkstation#38]
Hallo,
I installed Docker Toolbox together with Kitematic in order to automate the docker images.
However, Kitematic starts and drops error: 
`
Error: connect ENOENT //./pipe/docker_engine`

There is same error if I press RETRY.
If I press Use Virtualbox the error is 

`Virtualbox not installed. Please install it via the Docker Toolbox.`

Any help is apprechiated.

**Comment by pecigonzalo** [comment]
@drschlaumeier https://docs.docker.com/kitematic/ Kitematic is no longer supported, i believe its trying to user virtualbox.

**Comment by kkeybbs** [comment]
I make Kitematic works well with docker-machine-vmwareworkstation.
Check code [here](https://github.com/docker/kitematic/blob/master/src/utils/DockerMachineUtil.js), we know that virtualbox is hard code in Kitematic, so we just provides a fake VBoxManage.exe.

- Step 1, create a "default" machine with docker-machine-vmwareworkstation:
```
docker-machine create -d vmwareworkstation default
```
- Step2, create a fake VBoxManage
```
//compile with: cl VBoxManage.c
#include <stdio.h>
int main() {
  printf("6.0.0.127566\n");
  printf(" \"%s\" \n", "default");
  return 0;
}
```
- Step3, set env for Kitematic (I put step2's compiled binary to vbox)
```
set "VBOX_INSTALL_PATH=%cd%\vbox"
```
- step4, run Kitematic.exe. So Kitematic will check with the fake VBoxManage, but works with named pipe of docker-machine-vmware

**Comment by leonardochaia** [comment]
I'm working on this project called Timoneer which is a desktop UI (electron) for Docker.
https://github.com/leonardochaia/timoneer
