### ISSUE TITLE
vmware player requires separate download for vmware-vdiskmanager.exe and the driver can't find it

### ISSUE THREAD

**Issue by pessimism** [pecigonzalo/docker-machine-vmwareworkstation#41]
https://my.vmware.com/group/vmware/get-download?downloadGroup=VDDK65

() DBG | Unable to read registry key SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\vmware.exe\Path
() DBG | Error finding VMware root: The system cannot find the file specified.
() DBG | File not found: 'vmrun.exe'
() DBG | Unable to read registry key SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\vmware.exe\Path
() DBG | Error finding VMware root: The system cannot find the file specified.
() Calling .GetVersion
() DBG | File not found: 'vmware-vdiskmanager.exe'
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at docker-machine-driver-vmwareworkstation.exe
Launching plugin server for driver vmwareworkstation
Plugin server listening at address 127.0.0.1:50650
() DBG | Unable to read registry key SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\vmware.exe\Path
() DBG | Error finding VMware root: The system cannot find the file specified.
() DBG | File not found: 'vmrun.exe'
() DBG | Unable to read registry key SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\vmware.exe\Path
() DBG | Error finding VMware root: The system cannot find the file specified.
() DBG | File not found: 'vmware-vdiskmanager.exe'

the path detection logic needs improvement to accomodate vmware player which has the player, vmrun (from vmware VIX SDK) and vmware-vdiskmanager (from VDDK) all in different locations

**Comment by pecigonzalo** [comment]
Is this also related to VMWare Workstation 12?  #40

**Comment by pecigonzalo** [comment]
Closing issue as no updates from the reporter.
