### ISSUE TITLE
Improve error reporting when no NAT/DHCP based virtual network exists

### ISSUE THREAD

**Issue by WheelmanK** [pecigonzalo/docker-machine-vmwareworkstation#53]
I recently installed the docker-machine and vmware workstation driver using chocolatey and attempted to create a VM using the following command:

docker-machine --native-ssh create -d vmwareworkstation default

with the result being a VM that would not connect using SSH.
Consequently it was impossible to connect to the instance using docker commands

After running the process with debug enabled and doing research into other people reporting the same issue and that they accidently "fixed" it by reinstalling or resetting VMware Workstation I realized the issue stemmed from the fact I had deleted the default virtual network VMNet8 which is installed with Workstation.
VMNet8 is configured to use NAT and DHCP by default.  

When this driver is used to create a new docker machine it sets up the workstation environment to use a NAT based virtual network and assumes DHCP is enabled.  If a network with this configuration does not exist in the local VMware virtual network environment the setup of a new docker VM fails while waiting for SSH to connect.
The VM is created and will execute but it is impossible for docker to connect to it.

I request more thorough checking be performed on the VMware virtual network environment and if a network with the required setup is not present an error message be displayed informing the user of the discrepancy. 
An alternative solution is to provide the ability to the user to specify the virtual network the driver should use when creating the VM instance.

**Comment by pecigonzalo** [comment]
I dont know if this is possible, but ill give it a look.
