### ISSUE TITLE
Windows 10 not share my home dir

### ISSUE THREAD

**Issue by alexsapran** [pecigonzalo/docker-machine-vmwareworkstation#8]
Hi i used this with my vmware workstation and after it start the container when i ssh into the new machine i see that there is no mount of my host home directory.
VmWareworkstation version: 12.1.0 build-3272444
docker-machine: 0.5.6, build 61388e9 also tested it with 0.5.5 
When using the virtualbox i got the home directory in my /c/Users

**Comment by pecigonzalo** [comment]
Hi alex, i dont remember implementing this functionality and i dont think its implemented for vmware-fusion either but ill give it a look ASAP.

Cheers

**Comment by alexsapran** [comment]
Hi Peci,

For fusion it is working as i use the fusion driver for my osx installation. 
Thank you for your quick response. 

Regards Alex

**Comment by StefanScherer** [comment]
Yes, that would be great. Fusion does this probably here: https://github.com/docker/machine/blob/master/drivers/vmwarefusion/fusion_darwin.go#L360-L378

**Comment by StefanScherer** [comment]
The VirtualBox driver does this for lin/win/mac here: https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L426-L452

and returns the share name for windows here: https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox_windows.go#L93-L95

**Comment by pecigonzalo** [comment]
Excellent, im in the middle of a house move but ill get to work on this ASAP

**Comment by alexsapran** [comment]
:+1:

**Comment by abaldeo** [comment]
+1

**Comment by alexsapran** [comment]
@pecigonzalo do you have any update on this?

**Comment by pecigonzalo** [comment]
@alexsapran not yet sorry, im still moving (changing countries). I just received my laptop ill try to start working on this.

**Comment by pecigonzalo** [comment]
@alexsapran Till this is released on a new version (might be 20 days from now) you can download a build from here: 
https://ci.appveyor.com/project/pecigonzalo/docker-machine-vmwareworkstation/build/1.0.10.4

Go to version that fits you and from the artifacts section you can download a compiled binary

**Comment by alexsapran** [comment]
Hi @pecigonzalo 

The mounting of the home directory now works fine. 
One point here is that in cygwin the home path is `/c/Users` or `/cygdrive/c/Users` so the mount `/Users/` will not work all of the time cause when you are on the host machine and mount a folder then the actual path will be `/c/Users/....` and that path is not present inside the VM.

I do not know if the proper solution would be to mount as /c/Users or create a symlink inside the vm.
When i have some more time to debug i will try to review again. 

As a button line i think that the mount is working.
Thanks for fix Alex.

**Comment by StefanScherer** [comment]
The `/cygdrive/c` is only for the cygwin commands like bash etc. As docker-machine and the plugin are "normal" programs they still only see `c:\Users` so the mount point should work for normal shells as within a cygwin shell.

**Comment by pecigonzalo** [comment]
@StefanScherer Thanks, that should be correct.

**Comment by alexsapran** [comment]
Hi according to the docker documentation the windows path is `/c/Users`
Please see for more details here https://docs.docker.com/engine/userguide/containers/dockervolumes/

You are right @StefanScherer about the cygwin but docker-machine is not a normal program in the sense that it will try to map the host `c:\Users` to `/c/Users/` thus both shell i believe must resolve that path, maybe i am wrong.

Let me elaborate a bit further, when i start docker-machine and want to by mount a local folder with the container, then on that container if i do a `docker inspect <container id>` i will see that the path of the mounted folder will be `/c/Users/` so if now on the guest machine (the one provisioned by docker-machine) the path is mounted at `/Users/` then the container will not fail it will just create an empty folder at `/c/Users/...`.

I hope i provided enough information. 

Alex.

**Comment by darvin** [comment]
```
PS C:\Users\darvin> docker run -v /c/Users/:/mnt ubuntu ls /mnt
PS C:\Users\darvin> docker run -v //c/Users/:/mnt ubuntu ls /mnt
PS C:\Users\darvin> docker run -v /home/docker/:/mnt ubuntu ls /mnt
boot2docker, this is vmware speaking
log.log
PS C:\Users\darvin> docker run -v '//c/Users/:/mnt' ubuntu ls /mnt

PS C:\Users\darvin> docker run -it -v /c/Users/:/mnt ubuntu bash
PS C:\tools\cmder> docker inspect angry_jones
[
    {
        "Id": "3e533f2f31200a19fc348338336e2369364424e85ef3b37263868b67b2c05f16",
        "Created": "2016-03-21T15:35:33.289240023Z",
        "Path": "bash",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2540,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-03-21T15:35:33.454119669Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:97434d46f197df218f1eb18be3f7807dc276d086d50908358755bf090300e201",
        "ResolvConfPath": "/mnt/sda1/var/lib/docker/containers/3e533f2f31200a19fc348338336e2369364424e85ef3b37263868b67b2c05f16/resolv.conf",
        "HostnamePath": "/mnt/sda1/var/lib/docker/containers/3e533f2f31200a19fc348338336e2369364424e85ef3b37263868b67b2c05f16/hostname",
        "HostsPath": "/mnt/sda1/var/lib/docker/containers/3e533f2f31200a19fc348338336e2369364424e85ef3b37263868b67b2c05f16/hosts",
        "LogPath": "/mnt/sda1/var/lib/docker/containers/3e533f2f31200a19fc348338336e2369364424e85ef3b37263868b67b2c05f16/3e533f2f31200a19fc348338336e2369364424e85ef3b37263868b67b2c05f16-json.log",
        "Name": "/angry_jones",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/c/Users/:/mnt"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                27,
                101
            ],
            "Isolation": "",
            "CpuShares": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "KernelMemory": 0,
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/c/Users",
                "Destination": "/mnt",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "3e533f2f3120",
            "Domainname": "",
            "User": "",
            "AttachStdin": true,
            "AttachStdout": true,
            "AttachStderr": true,
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": true,
            "Env": [],
            "Cmd": [
                "bash"
            ],
            "Image": "ubuntu",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {},
            "StopSignal": "15"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "8d52a16abd7aeddd6438f08e2df044ddaa3b5c7781bf2d1af8a5613b0fa47dbd",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/8d52a16abd7a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "ef0b0d56a77f52c161f4a5c4abb9320028ae01fbaad9d2b1b60aa598372f2ffc",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "da93b71594338ba0015f7bcf3f21b9efe256533e2d6cb75127b2d4c9acb22368",
                    "EndpointID": "ef0b0d56a77f52c161f4a5c4abb9320028ae01fbaad9d2b1b60aa598372f2ffc",

                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]
PS C:\tools\cmder>
```

**Comment by darvin** [comment]
Powershell, plugin version 1.0.10.4

```
PS C:\Users\darvin> docker run -v '/c/Users:/mnt' ubuntu ls /mnt
PS C:\Users\darvin> docker run -v /c/Users:/mnt ubuntu ls /mnt
PS C:\Users\darvin> docker run -v //c/Users:/mnt ubuntu ls /mnt
PS C:\Users\darvin> docker run -v /home/docker:/mnt ubuntu ls /mnt
boot2docker, this is vmware speaking
log.log
PS C:\Users\darvin>
```

**Comment by pecigonzalo** [comment]
@darvin and @alexsapran 
The vmware driver maps `c:\users\` on the vm `/Users/`, this is what Virtualbox and VMWare fusion map to this folder, so i think this is the best solution to keep it consistent.

docker-machine is indeed a normal program but your docker command runs inside the VM so you use linux paths there you are not mapping from windows but from your boot2docker vm, and the VM maps from windows.
You should run `docker run -v /Users:/mnt ubuntu ls /mnt` and you should get the directory.

**Comment by alexsapran** [comment]
@pecigonzalo according to the docker documentation for windows the mount should be on /c/Users and not /Users.
Please see the link that i have attached in my previous comment (https://github.com/pecigonzalo/docker-machine-vmwareworkstation/issues/8#issuecomment-198255999).

```
If you are using Docker Machine on Mac or Windows, your Docker daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your /Users (OS X) or C:\Users (Windows) directory. So, you can mount files or directories on OS X using.

docker run -v /Users/<path>:/<container path> ...
On Windows, mount directories using:

docker run -v /c/Users/<path>:/<container path> ...`
```

Also if you see on this comment (https://github.com/pecigonzalo/docker-machine-vmwareworkstation/issues/8#issuecomment-175279658) for virtualbox it is `c/Users` the mount path for the share.

**Comment by pecigonzalo** [comment]
Ill submit a PR to them, i believe thats wrong as it makes it so instructions that works on 1 platform (osx/linux) does not work on Windows for no real benefit.

In this plugin right now, it works as i just said or it should.

**Comment by alexsapran** [comment]
But the docker deamon will send the path /c/Users/.... to the guest machine so that path must be valid there too. 
The unification you mention is another issue completely.

**Comment by pecigonzalo** [comment]
The docker daemon will send that if you use `-v /c/Users:/mnt` just use `-v /Users:mnt`

**Comment by alexsapran** [comment]
I am using docker-compose so i cannot send the path as `/Users/`
What you say only works if i mount the path with -v /Users/Alexandros/.... 
The problem is that this does not work with docker-compose.
docker-compose uses the paths just like the documentation mentions, so if for example i start a container with docker compose then the mounted path will be /c/Users/Alexandros.....

```
....
 "GraphDriver": {                                                   
     "Name": "aufs",                                                
     "Data": null                                                   
 },                                                                 
 "Mounts": [                                                        
     {                                                              
         "Source": "/c/Users/Alexandros/git/www",           
         "Destination": "/var/www/html",                            
         "Mode": "rw",                                              
         "RW": true,                                                
         "Propagation": "rprivate"                                  
     }                                                              
 ],                                                                 
 "Config": {                                                        
     "Hostname": "f646a9ca62be",                                    
     "Domainname": "",                                              
     "User": "",                                                    
     "AttachStdin": false,                                          
     "AttachStdout": false,                                         
     "AttachStderr": false,                                         
     "Tty": false,                                                  
     "OpenStdin": false,                                            
     "StdinOnce": false,                                            
....
```

If you feel that we should open a PR to docker-compose then can i suggest to open it there, with ref here and in the meanwhile let's try to make this work with the current docker & docker-compose functionality?

**Comment by pecigonzalo** [comment]
Can you show me your docker compose config?

**Comment by alexsapran** [comment]
with this you can reproduced

```
test: 
   image: busybox
   volumes:
      - ./www:/var/www/html
   entrypoint: ls /var/www/html
```

**Comment by pecigonzalo** [comment]
https://github.com/docker/compose/blob/4c4e94bc19dd8bf185c3d810d3f5e123797ea754/compose/config/types.py#L108

There, that seems to be compose causing the issues, not the driver.
Given you are running from `c:/Users/username/project`
They are converting your `./www` to full path EG: `c:/Users/username/project/www`
and then converting that to linuxstyle
`/c/Users/username`

try using full path in your volume config, see if that works.
Ill revise this tomorrow and try to figure out the best solution that combines all of this things.
Please open a new issue and link this one.

**Comment by darvin** [comment]
```
docker run -v /Users:/mnt ubuntu ls /mnt
```

does work, thank you so much!

**Comment by alexsapran** [comment]
I do not think that this is a docker-compose problem. This i the default expected behaviour for the docker.
Please review the documentation, crealy it states what i say and what you discovered from the code, that for the windows machines the path must be `/c/Users/...`.
I do not think we should change docker compose or docker to use `/Users/...`
Why we just dont mount it as the documentation state?

**Comment by pecigonzalo** [comment]
@alexsapran
First of all, the documentation only talks about the bundled drivers, there is no 3rd party driver guideline that states i need to mount it anywhere.
The code from docker-compose only states a path conversion, it does state any guidelines either.

docker-compose is no 100% compatible with docker-machine, that is something docker-compose needs to fix. EG: If your work from any other location that your user profile, mounting does not happen as the only/default mount location as far as i recall is /Users (OSX) /home (Linux) C:/Users (Windows).
All the drivers for docker-machine should be using a consistent approach, which is not the case currently. If i fix it for docker-compose i would be breaking consistency for docker_cli->docker-machine  (instruction that work on linux/osx docker-machine would not work on windows).

Aside from all that, if you want to further discus this, as i said open a new issue, this one is resolved.

Thanks

**Comment by alexsapran** [comment]
Sorry but i do not understand your answer.
When you say that there are no guidelines for 3rd party drivers you are saying that your driver will just mount the path to a different location and break the existing docker-compose. 
i will add another ticket but this makes your plugin unusable both to me and the team i am working with.

**Comment by pecigonzalo** [comment]
Please, open the new incident, i have an idea on how to fix this for you and keep it working as i would prefer.

**Comment by alexsapran** [comment]
i will just updating a cluster and need all my focus there, but until the end of day i will create it, i do not want to just create smthng with just a phase mounting issue and docker-compose :smile: 

Thanks you for your time and effort.
