### ISSUE TITLE
[v1.0.0] Default SSH user does not get created in the VM

### ISSUE THREAD

**Issue by artemgordinskiy** [pecigonzalo/docker-machine-vmwareworkstation#9]
Hi,

I've noticed that after creating a brand new Docker Machine using this driver, the specified default SSH user `B2DUser` does not get created in the virtual machine. Fortunately, user `docker` still does, so  it doesn't appear to be that big of a problem.

Sorry if I'm confusing SSH users with some other kind of users.

Docker: 1.10.0
Docker Machine: 0.6.0
VMware® Workstation 12 Pro 12.1.0 build-3272444
OS: Windows 8

P.S. The driver works really well overall, great job!

**Comment by pecigonzalo** [comment]
You are correct, the README.md is wrong, the default is docker. Ill correct it as soon as i get a chance.
Thanks for the report!

**Comment by pecigonzalo** [comment]
Fixed in #17
